version: "3.9"
services:
  bot:
    container_name: dman_v3
    image: hummingbot/hummingbot:development
    volumes:
    - ./hummingbot_files/conf:/home/hummingbot/conf
    - ./hummingbot_files/conf/connectors:/home/hummingbot/conf/connectors
    - ./hummingbot_files/conf/strategies:/home/hummingbot/conf/strategies
    - ./hummingbot_files/logs:/home/hummingbot/logs
    - ./hummingbot_files/data:/home/hummingbot/data
    - ./hummingbot_files/scripts:/home/hummingbot/scripts
    - ./hummingbot_files/controllers:/home/hummingbot/hummingbot/smart_components/controllers
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
#    environment:
#      - CONFIG_PASSWORD=a
#      - CONFIG_FILE_NAME=v2_trend-following_drupman_v1.py
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: 5
    tty: true
    stdin_open: true